{% set name = "josepy" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/josepy-{{ version }}.tar.gz
  sha256: e7d7acd2fe77435cda76092abe4950bb47b597243a8fb733088615fa6de9ec40

build:
  number: 0
  noarch: python
  entry_points:
    - jws = josepy.jws:CLI.run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.8
  run:
    - cryptography >=1.5
    - pyopenssl >=0.13
    - python >={{ python_min }}
    - setuptools >=1.0

test:
  imports:
    - josepy
  commands:
    - pip check
    - jws --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/certbot/josepy
  summary: JOSE protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
