{% set name = "josepy" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/josepy-{{ version }}.tar.gz
  sha256: 308b3bf9ce825ad4d4bba76372cf19b5dc1c2ce96a9d298f9642975e64bd13dd

build:
  number: 0
  noarch: python
  entry_points:
    - jws = josepy.jws:CLI.run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography >=1.5
    - pyopenssl >=0.13
    - python >=3.6
    - setuptools >=1.0

test:
  imports:
    - josepy
  commands:
    - pip check
    - jws --help
  requires:
    - pip

about:
  home: https://github.com/certbot/josepy
  summary: JOSE protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
